git lfs install
git lfs track "*.exe"
git lfs track "*.zip"
git lfs track "*.rar"
git lfs track "*.7z"
git lfs track "*.py"
git lfs track "*.bat"
git lfs track "*.cmd"
git lfs track "*.zim"
git lfs track "*.reg"
git lfs track "*.apk"
git lfs track "*.asf"
git lfs track "*.avi"
git lfs track "*.gz"
git lfs track "*.gzip"
git lfs track "*.img"
git lfs track "*.iso"
git lfs track "*.m4a"
git lfs track "*.mkv"
git lfs track "*.mov"
git lfs track "*.msi"
git lfs track "*.msu"
git add .gitattributes